# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='roll',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='sub',
            field=models.IntegerField(default=0),
        ),
    ]
