# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='roll',
            new_name='Chemistry',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='sub',
            new_name='Maths',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='post',
            name='Physics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='RollNo',
            field=models.IntegerField(default=0),
        ),
    ]
